site:
  title: CIDER Docs
  url: https://docs.cider.mx
  start_page: cider::index.adoc
  keys:
    google_analytics: "G-XQLJHQHH8Q"
urls:
  latest_version_segment: latest
content:
  sources:
    - url: https://github.com/clojure-emacs/cider.git
      branches: master
      tags:
        [
          "v1.0.0",
          "v1.1.1",
          "v1.2.0",
          "v1.3.0",
          "v1.4.0",
          "v1.5.0",
          "v1.6.0",
          "v1.7.0",
          "v1.8.0",
          "v1.9.0",
          "v1.11.0",
          "v1.12.0",
          "v1.13.0",
          "v1.14.0",
          "v1.15.0",
          "v1.16.0",
          "v1.17.0",
          "v1.18.0-antora",
          "v1.19.0",
          "v1.20.0",
          "v1.22.2",
          "v2.0.1",
        ]
      start_path: doc
    - url: https://github.com/clojure-emacs/cider-nrepl.git
      branches: master
      tags: ["v0.62.2"]
      start_path: doc
asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    linkattrs: ""
    toc: ~
    page-pagination: ""
  extensions:
    - "@asciidoctor/tabs"
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
    - path: css/site-extra.css
      contents: ./supplemental-ui/css/site-extra.css
    - path: img/favicon.ico
      contents: ./supplemental-ui/img/favicon.ico
    - path: partials/footer-content.hbs
      contents: ./supplemental-ui/partials/footer-content.hbs
    - path: partials/head-meta.hbs
      contents: ./supplemental-ui/partials/head-meta.hbs
    - path: partials/header-content.hbs
      contents: ./supplemental-ui/partials/header-content.hbs
    # Assets of the tabs extension, taken straight from the npm package.
    - path: css/vendor/tabs.css
      contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css
    - path: js/vendor/tabs.js
      contents: ./node_modules/@asciidoctor/tabs/dist/js/tabs.js
output:
  dir: build/site
