== CIDER.mx

The site is generated from the asciidoc files in the link:https://github.com/clojure-emacs/cider/tree/master/doc[doc] folder of nREPL's GitHub repo and is published to https://docs.cider.mx.
link:https://antora.org[Antora] is used to convert the manual into HTML.
The filesystem layout is described at https://docs.antora.org/antora/2.0/component-structure/

To make changes to the manual you simply have to change the files under `doc`.
The manual will be regenerated manually periodically.

You can build the documentation locally from the link:https://github.com/clojure-emacs/cider-site[cider-site] repo.

[source]
----
$ cd cider-site
$ npm install
$ antora --pull site.yml
----

TIP: If `npm install` fails, see link:https://docs.antora.org/antora/2.0/install/troubleshoot-nodegit/[Antora's troubleshooting documentation].

After you're done with the initial setup you can use the `deploy` script to push changes to the site:

[source]
----
./deploy
----

NOTE: You'll need commit access to the repository for this to work.

To check the generated site you can simply open `docs/index.html` in your favourite browser.

If you want to make changes to the manual's page structure you'll have to edit
link:https://github.com/clojure-emacs/cider/blob/master/doc/modules/ROOT/nav.adoc[nav.adoc].
